-- msp_resources / msp_resource_assignments -- CORE-OWNED SCHEMA
--
-- NOT AN ALEMBIC REVISION AND NOT RUN BY FINANCE.
--
-- Finance's Alembic owns the Finance schema and nothing else; the header of
-- scripts/demo/core_mirror.sql states that rule, and these two tables are Core's. They are
-- delivered as SQL so the Core/Planning team applies them with their own migration process
-- and keeps ownership where the data is produced.
--
-- Run PRECHECK first. Run this by hand. It creates tables and nothing else: no backfill, no
-- row is written, and no existing Core object is altered.
--
-- WHAT THE COLUMNS MEAN
--   resource_quantity / planned_quantity are PHYSICAL quantities -- kilograms, cubic metres
--   -- read from MPXJ's Material field. They are not Work. Work is time, measured in hours,
--   and is stored separately so nobody can mistake one for the other.
--
--   source_cost / source_actual_cost / standard_rate are REFERENCE ONLY. The authoritative
--   price in Finance is price_versions and the authoritative actual cost is a confirmed
--   invoice. A rate typed into a Resource Sheet is neither.
--
--   resource_quantity_unit comes from Resource.Initials in the file this was designed
--   against, because Material Label was empty on all 81 resources there. That is one
--   planner's convention, not a Microsoft Project standard, which is why the raw initials
--   and the unit source are both stored: a later file that fills Material Label properly
--   must not silently become unitless.

BEGIN;

-- Fail loudly rather than half-applying onto an unexpected schema.
DO $$
BEGIN
    IF to_regclass('public.msp_snapshots') IS NULL THEN
        RAISE EXCEPTION 'msp_snapshots is missing: this is not a BAMBO Core database';
    END IF;
    IF to_regclass('public.msp_tasks') IS NULL THEN
        RAISE EXCEPTION 'msp_tasks is missing: this is not a BAMBO Core database';
    END IF;
    IF to_regclass('public.msp_resources') IS NOT NULL
       OR to_regclass('public.msp_resource_assignments') IS NOT NULL THEN
        RAISE EXCEPTION
            'msp_resources or msp_resource_assignments already exists -- stop and inspect. '
            'This script creates, it does not adopt.';
    END IF;
END $$;


CREATE TABLE msp_resources (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id             bigint        NOT NULL,

    -- Native MSP identity. UID is the key: across two saved versions of one real schedule
    -- every task GUID had been regenerated while every UID survived, so GUID is kept for
    -- diagnostics and is deliberately not an identity anywhere.
    resource_uid            integer       NOT NULL,
    resource_guid           text,

    resource_name           text,
    native_type             text          NOT NULL,
    bambo_resource_type     text,

    -- The Resource Sheet "Quantity" column: MPXJ Resource.Material.
    resource_quantity       numeric(18,6),
    resource_quantity_unit  text,
    -- Which field the unit was taken from, so a later file that changes convention is
    -- visible instead of silently reinterpreted.
    quantity_unit_source    text,

    initials                text,
    material_label          text,
    resource_group          text,
    code                    text,

    max_units               numeric(18,6),

    standard_rate           numeric(18,4),
    overtime_rate           numeric(18,4),
    cost_per_use            numeric(18,4),

    work                    numeric(18,6),
    actual_work             numeric(18,6),
    remaining_work          numeric(18,6),

    source_cost             numeric(18,4),
    source_actual_cost      numeric(18,4),
    source_remaining_cost   numeric(18,4),

    raw_fields_json         jsonb,
    created_at              timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT msp_resources_snapshot_id_fkey
        FOREIGN KEY (snapshot_id) REFERENCES msp_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT msp_resources_native_type_check
        CHECK (native_type IN ('WORK', 'MATERIAL', 'COST')),
    -- NULL is a real state: MSP has no labour/equipment distinction, and guessing one from
    -- a resource name is how a crane becomes a bricklayer.
    CONSTRAINT msp_resources_bambo_type_check
        CHECK (bambo_resource_type IS NULL
               OR bambo_resource_type IN ('material', 'labor', 'equipment', 'general_cost')),
    CONSTRAINT msp_resources_quantity_check
        CHECK (resource_quantity IS NULL OR resource_quantity >= 0),
    CONSTRAINT msp_resources_quantity_unit_source_check
        CHECK (quantity_unit_source IS NULL
               OR quantity_unit_source IN ('material_label', 'initials', 'custom_field', 'other')),
    CONSTRAINT msp_resources_snapshot_uid_key UNIQUE (snapshot_id, resource_uid),
    -- Lets an assignment reference a resource without being able to reach across snapshots.
    CONSTRAINT msp_resources_id_snapshot_key UNIQUE (id, snapshot_id)
);

CREATE INDEX msp_resources_snapshot_idx    ON msp_resources (snapshot_id);
CREATE INDEX msp_resources_native_type_idx ON msp_resources (snapshot_id, native_type);
CREATE INDEX msp_resources_guid_idx        ON msp_resources (resource_guid)
    WHERE resource_guid IS NOT NULL;

COMMENT ON TABLE  msp_resources IS
    'MSP Resource Sheet, one row per resource per snapshot. Owned by Core/Planning; Finance reads only.';
COMMENT ON COLUMN msp_resources.resource_uid IS
    'Native MSP Resource UID. The identity. GUID is regenerated on save and must not be used as one.';
COMMENT ON COLUMN msp_resources.resource_quantity IS
    'Physical quantity from MPXJ Resource.Material -- the Resource Sheet Quantity column. Not Work, not Max Units.';
COMMENT ON COLUMN msp_resources.resource_quantity_unit IS
    'Unit of resource_quantity. quantity_unit_source records which MSP field it was read from.';
COMMENT ON COLUMN msp_resources.bambo_resource_type IS
    'BAMBO-wide classification, shared by Finance, procurement and project control. NULL when MSP gives no basis to classify.';
COMMENT ON COLUMN msp_resources.standard_rate IS
    'Reference only. The authoritative price history is the Finance price_versions table.';


CREATE TABLE msp_resource_assignments (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id             bigint        NOT NULL,

    assignment_uid          integer       NOT NULL,
    task_uid                integer       NOT NULL,
    -- Null on an assignment MSP left unlinked: 12 of 727 in the reference file. Kept rather
    -- than dropped, because work recorded against an unlinked assignment still has to be
    -- countable somewhere a reader can see it.
    resource_uid            integer,

    units                   numeric(18,6),

    planned_work            numeric(18,6),
    actual_work             numeric(18,6),
    remaining_work          numeric(18,6),

    -- The granular quantity. This, not the resource total, is what a WBS rollup may use.
    planned_quantity        numeric(18,6),
    actual_quantity         numeric(18,6),
    remaining_quantity      numeric(18,6),
    quantity_unit           text,

    assignment_work_complete_percent numeric(7,4),

    source_cost             numeric(18,4),
    source_actual_cost      numeric(18,4),
    source_remaining_cost   numeric(18,4),

    raw_fields_json         jsonb,
    created_at              timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT msp_resource_assignments_snapshot_id_fkey
        FOREIGN KEY (snapshot_id) REFERENCES msp_snapshots(id) ON DELETE CASCADE,
    -- Composite, so an assignment cannot name a resource from another snapshot. The same
    -- idiom msp_snapshots already uses for msp_file_versions(id, project_id).
    CONSTRAINT msp_resource_assignments_resource_fkey
        FOREIGN KEY (snapshot_id, resource_uid)
        REFERENCES msp_resources (snapshot_id, resource_uid) ON DELETE RESTRICT,
    CONSTRAINT msp_resource_assignments_snapshot_uid_key UNIQUE (snapshot_id, assignment_uid),
    CONSTRAINT msp_resource_assignments_planned_quantity_check
        CHECK (planned_quantity IS NULL OR planned_quantity >= 0),
    CONSTRAINT msp_resource_assignments_actual_quantity_check
        CHECK (actual_quantity IS NULL OR actual_quantity >= 0),
    CONSTRAINT msp_resource_assignments_remaining_quantity_check
        CHECK (remaining_quantity IS NULL OR remaining_quantity >= 0),
    -- A quantity with no unit is a number nobody can read. Refused at the database.
    CONSTRAINT msp_resource_assignments_quantity_unit_check
        CHECK (quantity_unit IS NOT NULL
               OR (planned_quantity IS NULL AND actual_quantity IS NULL
                   AND remaining_quantity IS NULL))
);

CREATE INDEX msp_resource_assignments_snapshot_idx ON msp_resource_assignments (snapshot_id);
CREATE INDEX msp_resource_assignments_task_idx     ON msp_resource_assignments (snapshot_id, task_uid);
CREATE INDEX msp_resource_assignments_resource_idx ON msp_resource_assignments (snapshot_id, resource_uid);

COMMENT ON TABLE  msp_resource_assignments IS
    'MSP resource assignments, one row per task-resource assignment per snapshot. Owned by Core/Planning; Finance reads only.';
COMMENT ON COLUMN msp_resource_assignments.task_uid IS
    'Native msp_tasks.uid. No foreign key: msp_tasks carries no UNIQUE (snapshot_id, uid) to reference. See the runbook.';
COMMENT ON COLUMN msp_resource_assignments.planned_quantity IS
    'Physical quantity from MPXJ Assignment.Material. The task-granular figure a WBS rollup may use.';
COMMENT ON COLUMN msp_resource_assignments.actual_quantity IS
    'From MPXJ Assignment.ActualMaterial. NULL means not reported -- never zero by assumption.';
COMMENT ON COLUMN msp_resource_assignments.source_actual_cost IS
    'Reference only. The authoritative actual cost is a confirmed Finance invoice.';

COMMIT;
