"""Regenerate `seed.sql` from the rules the frontend's mock adapters use.

Run this whenever the mock data changes:

    python -m devhost.generate_seed_sql

The output is committed, so the seed itself is plain, reviewable SQL. This script exists
only to keep the 53 procedurally generated invoices in step with
`frontend/src/adapters/mock/invoices-adapter.js`, which builds them from an index rather
than listing them.
"""

from pathlib import Path
from uuid import UUID

from . import seed

OUT = Path(__file__).resolve().parent / "seed.sql"

# frontend/src/adapters/mock/invoices-adapter.js
STATUSES = ["draft", "awaitingConfirmation", "confirmed", "voided", "corrected"]
SOURCES = ["manual", "image", "voice"]
INVOICE_COUNT = 53
FIRST_INVOICE_INDEX = 1
REBAR_LINE_AMOUNT = 100_000_000


def quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int,)):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def invoice_uuid(index: int) -> UUID:
    return UUID(f"40000000-0000-4000-8000-{index:012d}")


def mock_invoice(index: int) -> dict:
    """Reproduce makeInvoice(index, context) from the mock adapter."""
    status = STATUSES[(index - 1) % len(STATUSES)]
    source = SOURCES[(index - 1) % len(SOURCES)]
    raw_total = 120_000_000 + index * 1_750_000
    day = ((index - 1) % 28) + 1
    if index % 3 == 0:
        vendor = "تأمین تجهیزات سازه نمونه"
    elif index % 2 == 0:
        vendor = "شرکت مصالح پایدار نمونه"
    else:
        vendor = "فروشگاه ساختمانی بامبو نمونه"
    discount = 500_000 if index % 4 == 0 else 0
    tax = 1_200_000 if index % 3 == 0 else 0
    shipping = 750_000 if index % 5 == 0 else 0
    reversed_status = status in ("voided", "corrected")
    return {
        "id": invoice_uuid(index),
        "number": f"ف-{index:03d}",
        "date": f"2026-07-{day:02d}",
        "vendor": vendor,
        "description": ("خرید و تأمین اقلام موردنیاز عملیات اجرایی طبق صورت‌جلسه کارگاه"
                        if index % 4 == 0 else "فاکتور نمایشی برای توسعه رابط کاربری"),
        "source": source,
        "status": status,
        "version": 1 if status == "draft" else 2 if status == "awaitingConfirmation" else 3,
        "idempotency_key": f"seed-invoice-{index:03d}",
        "discount": discount,
        "tax": tax,
        "shipping": shipping,
        "other": 0,
        "raw_total": raw_total,
        "final": raw_total - discount + tax + shipping,
        "sign": -1 if status == "voided" else 1,
        "original": invoice_uuid(FIRST_INVOICE_INDEX) if reversed_status else None,
        "confirmed": status in ("confirmed", "voided", "corrected"),
        "created_at": f"2026-07-{day:02d}T08:30:00Z",
        "general_amount": raw_total - REBAR_LINE_AMOUNT,
    }


def allocate(total: int, weights: list[int]) -> list[int]:
    """Split an adjustment across lines by weight, remainder on the last line."""
    if total == 0 or not weights:
        return [0] * len(weights)
    whole = sum(weights)
    parts = [round(total * weight / whole) for weight in weights[:-1]]
    return parts + [total - sum(parts)]


def build() -> str:
    org, project, actor = quote(seed.ORGANIZATION_ID), quote(seed.PROJECT_ID), quote(seed.ACTOR_ID)
    now = quote(seed.NOW.isoformat())
    out: list[str] = [
        "-- Generated by devhost/generate_seed_sql.py. Do not edit by hand.",
        "-- Mirrors the reference dataset in frontend/src/adapters/mock/.",
        "",
        "BEGIN;",
        "",
        "-- Project settings",
        "INSERT INTO finance_project_settings"
        "(id,organization_id,project_id,revision,gross_built_area,currency,effective_from,reason,created_by,created_at)"
        f" VALUES({quote(seed.SETTINGS_ID)},{org},{project},1,{quote(seed.GROSS_BUILT_AREA)},'IRR',"
        f"{quote(seed.SETTINGS_EFFECTIVE_FROM)},{quote(seed.SETTINGS_REASON)},{actor},{now});",
        "",
        "-- Finance resources",
    ]

    for resource_id, kind, code, title, base_unit, dimension, external_id in seed.RESOURCES:
        out.append(
            "INSERT INTO finance_resources"
            "(id,organization_id,project_id,resource_type,code,title,base_unit,dimension,"
            "external_resource_id,created_by,created_at)"
            f" VALUES({quote(resource_id)},{org},{project},{quote(kind)},{quote(code)},{quote(title)},"
            f"{quote(base_unit)},{quote(dimension)},{quote(external_id)},{actor},{now});")

    out += ["", "-- Estimate lines"]
    for line_id, resource_id, activity, assignment, quantity, price in seed.ESTIMATE_LINES:
        out.append(
            "INSERT INTO estimate_lines"
            "(id,organization_id,project_id,resource_id,activity_external_id,assignment_external_id,"
            "original_quantity,original_unit_price_irr,source,created_by,created_at)"
            f" VALUES({quote(line_id)},{org},{project},{quote(resource_id)},{quote(activity)},"
            f"{quote(assignment)},{quote(quantity)},{quote(price)},'progress_feed',{actor},{now});")

    out += ["", "-- Estimate revisions (the mock's revisedQuantity)"]
    for index, (line_id, revision, previous, new_quantity, reason) in enumerate(seed.ESTIMATE_REVISIONS, 1):
        out.append(
            "INSERT INTO estimate_revisions"
            "(id,organization_id,project_id,estimate_line_id,revision,previous_quantity,new_quantity,"
            "reason,created_by,created_at)"
            f" VALUES({quote(UUID(f'31000000-0000-4000-8000-{index:012d}'))},{org},{project},"
            f"{quote(line_id)},{revision},{quote(previous)},{quote(new_quantity)},{quote(reason)},"
            f"{actor},{now});")

    out += ["", "-- Price versions"]
    for price_id, resource_id, scope_kind, version, price, effective_from in seed.PRICE_VERSIONS:
        out.append(
            "INSERT INTO price_versions"
            "(id,organization_id,project_id,resource_id,scope_kind,version,unit_price_irr,"
            "effective_from,reason,created_by,created_at)"
            f" VALUES({quote(price_id)},{org},{project},{quote(resource_id)},{quote(scope_kind)},"
            f"{version},{quote(price)},{quote(effective_from)},{quote('ثبت نسخه قیمت')},{actor},{now});")

    out += ["", "-- Unit conversions"]
    for (conversion_id, scope_kind, version, source_unit, target_unit,
         dimension, factor, effective_from) in seed.UNIT_CONVERSIONS:
        out.append(
            "INSERT INTO unit_conversions"
            "(id,organization_id,project_id,scope_kind,version,source_unit,target_unit,dimension,"
            "factor,effective_from,reason,created_by,created_at)"
            f" VALUES({quote(conversion_id)},{org},{project},{quote(scope_kind)},{version},"
            f"{quote(source_unit)},{quote(target_unit)},{quote(dimension)},{quote(factor)},"
            f"{quote(effective_from)},{quote('تبدیل واحد پایه')},{actor},{now});")

    out += ["", "-- Progress snapshot references (the feed itself is served by the host port)"]
    for snapshot in seed.PROGRESS_SNAPSHOTS:
        out.append(
            "INSERT INTO progress_snapshot_refs"
            "(id,organization_id,project_id,progress_snapshot_id,source_file_version_id,"
            "source_file_name_safe,reporting_date,snapshot_status,imported_by,imported_at,created_at)"
            f" VALUES({quote(snapshot['ref_id'])},{org},{project},"
            f"{quote(snapshot['progress_snapshot_id'])},{quote(snapshot['source_file_version_id'])},"
            f"{quote(snapshot['source_file_name_safe'])},{quote(snapshot['reporting_date'])},'ready',"
            f"{quote(seed.IMPORTER_ID)},{quote(snapshot['imported_at'].isoformat())},"
            f"{quote(snapshot['imported_at'].isoformat())});")

    override = seed.PROGRESS_OVERRIDE
    out += ["", "-- Manual progress override recorded by the mock feed"]
    out.append(
        "INSERT INTO progress_overrides"
        "(id,organization_id,project_id,estimate_line_id,progress_snapshot_ref_id,computed_value,"
        "override_value,reason,created_by,created_at)"
        f" VALUES({quote(override['id'])},{org},{project},{quote(override['estimate_line_id'])},"
        f"{quote(override['progress_snapshot_ref_id'])},{quote(override['computed_value'])},"
        f"{quote(override['override_value'])},{quote(override['reason'])},"
        f"{quote(override['created_by'])},{quote(override['created_at'].isoformat())});")

    out += ["", f"-- {INVOICE_COUNT} invoices, reproducing makeInvoice() from the mock adapter."]
    rebar_line, permit_line = seed.ESTIMATE_LINES[0][0], seed.ESTIMATE_LINES[4][0]
    for index in range(FIRST_INVOICE_INDEX, INVOICE_COUNT + 1):
        invoice = mock_invoice(index)
        out.append(
            "INSERT INTO invoices"
            "(id,organization_id,project_id,invoice_number,invoice_date,vendor_name,description,source,"
            "status,discount_irr,tax_irr,shipping_irr,other_costs_irr,final_amount_irr,"
            "financial_effect_sign,idempotency_key,original_invoice_id,version,submitted_by,"
            "confirmed_by,confirmed_at,created_at,updated_at)"
            f" VALUES({quote(invoice['id'])},{org},{project},{quote(invoice['number'])},"
            f"{quote(invoice['date'])},{quote(invoice['vendor'])},{quote(invoice['description'])},"
            f"{quote(invoice['source'])},{quote(invoice['status'])},{invoice['discount']},"
            f"{invoice['tax']},{invoice['shipping']},{invoice['other']},{invoice['final']},"
            f"{invoice['sign']},{quote(invoice['idempotency_key'])},{quote(invoice['original'])},"
            f"{invoice['version']},{actor},"
            f"{actor if invoice['confirmed'] else 'NULL'},"
            f"{quote('2026-08-01T09:15:00Z') if invoice['confirmed'] else 'NULL'},"
            f"{quote(invoice['created_at'])},{quote(invoice['created_at'])});")

        weights = [REBAR_LINE_AMOUNT, invoice["general_amount"]]
        discounts = allocate(invoice["discount"], weights)
        taxes = allocate(invoice["tax"], weights)
        shippings = allocate(invoice["shipping"], weights)
        others = allocate(invoice["other"], weights)
        lines = [
            (rebar_line, seed.REBAR, "1250.0000", "kg", 80000, REBAR_LINE_AMOUNT, "تحویل مرحله اول"),
            (permit_line, seed.PERMIT, None, None, None, invoice["general_amount"], "هزینه عمومی مرتبط"),
        ]
        for position, (estimate_line, resource, quantity, unit, unit_price, raw, note) in enumerate(lines):
            final_line = raw - discounts[position] + taxes[position] + shippings[position] + others[position]
            line_id = UUID(f"41000000-0000-4000-8000-{index * 10 + position:012d}")
            out.append(
                "INSERT INTO invoice_lines"
                "(id,organization_id,project_id,invoice_id,estimate_line_id,resource_id,quantity,unit,"
                "unit_price_snapshot_irr,raw_amount_irr,allocated_discount_irr,allocated_tax_irr,"
                "allocated_shipping_irr,allocated_other_costs_irr,final_line_amount_irr,description,created_at)"
                f" VALUES({quote(line_id)},{org},{project},{quote(invoice['id'])},{quote(estimate_line)},"
                f"{quote(resource)},{quote(quantity)},{quote(unit)},{quote(unit_price)},{raw},"
                f"{discounts[position]},{taxes[position]},{shippings[position]},{others[position]},"
                f"{final_line},{quote(note)},{quote(invoice['created_at'])});")

    out += ["", "-- Audit trail for the events the seed represents"]
    audit = [
        ("finance_settings.revised", "finance_project_settings", seed.SETTINGS_ID, seed.SETTINGS_REASON),
        ("price_version.created", "price_versions", seed.PRICE_VERSIONS[1][0], "به‌روزرسانی قیمت پروژه"),
        ("progress_override.created", "progress_overrides", override["id"], override["reason"]),
        ("invoice.confirmed", "invoices", invoice_uuid(3), None),
        ("invoice.confirmed", "invoices", invoice_uuid(8), None),
    ]
    for index, (action, entity_type, entity_id, reason) in enumerate(audit, 1):
        out.append(
            "INSERT INTO finance_audit_events"
            "(id,organization_id,project_id,actor_user_id,action,entity_type,entity_id,reason,occurred_at)"
            f" VALUES({quote(UUID(f'90000000-0000-4000-8000-{index:012d}'))},{org},{project},{actor},"
            f"{quote(action)},{quote(entity_type)},{quote(entity_id)},{quote(reason)},{now});")

    out += ["", "COMMIT;", ""]
    return "\n".join(out)


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT} ({len(OUT.read_text(encoding='utf-8').splitlines())} lines)")
