"""Regenerate `seed.sql` from the scenario defined in `devhost/seed.py`.

Run this whenever the scenario changes:

    python -m devhost.generate_seed_sql

The output is committed, so the seed itself stays plain, reviewable SQL. This script exists
because the invoices are the one part of the fixture that is easier to state as a plan --
"eight rebar deliveries of fifty tonnes" -- than as fifty-three hand-written rows.

WHAT THE INVOICE PLAN HAS TO GET RIGHT
The live report counts invoice lines whose invoice is `confirmed`, `voided` or `corrected`,
multiplied by the invoice's financial sign. So:

  * the confirmed batches carry the whole actual cost, and their material quantities are
    also the stock figure that reduces the money still required;
  * each reversal pair is one voided document and one corrected replacement at the same
    amount, so the pair contributes exactly nothing -- which is what a correct reversal
    should do, and is worth showing;
  * drafts and awaiting-confirmation invoices contribute nothing at all. They exist so the
    invoice list has something to page through.
"""

from pathlib import Path
from uuid import UUID

from . import seed

OUT = Path(__file__).resolve().parent / "seed.sql"

SOURCES = ["manual", "image", "voice"]
FIRST_INVOICE_INDEX = 1


def quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int,)):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def invoice_uuid(index: int) -> UUID:
    return UUID(f"40000000-0000-4000-8000-{index:012d}")


def invoice_plan() -> list[dict]:
    """Every invoice to write, in order, as plain data.

    Amounts are toman in `seed.py` and rial here: one place converts, so a batch cannot be
    written in one unit and totalled in the other.
    """
    plan: list[dict] = []
    index = FIRST_INVOICE_INDEX

    def add(**fields):
        nonlocal index
        day = ((index - 1) % 28) + 1
        month = 5 + ((index - 1) // 28)
        fields.setdefault("date", f"2026-{month:02d}-{day:02d}")
        fields["index"] = index
        fields["id"] = invoice_uuid(index)
        fields["number"] = f"ف-{index:03d}"
        fields["source"] = SOURCES[(index - 1) % len(SOURCES)]
        fields["idempotency_key"] = f"seed-invoice-{index:03d}"
        plan.append(fields)
        index += 1

    for resource, line, count, quantity, unit, amount, vendor, note in seed.INVOICE_BATCHES:
        for _ in range(count):
            add(status="confirmed", sign=1, vendor=vendor, description=note,
                lines=[(line, resource, quantity, unit, int(seed.T(amount)), note)])

    # A reversal and the corrected document that replaced it, at equal amounts. Each pair
    # nets to zero; the first confirmed invoice stands in as the original both refer to.
    original = invoice_uuid(FIRST_INVOICE_INDEX)
    reversal = int(seed.T(seed.REVERSAL_AMOUNT))
    for _ in range(seed.REVERSAL_PAIRS):
        add(status="voided", sign=-1, vendor="فولاد گستر نمونه", original=original,
            description="ابطال فاکتور اشتباه ثبت‌شده",
            lines=[(seed.LINE[1], seed.REBAR, seed.REVERSAL_QUANTITY, "kg", reversal,
                    "ابطال تحویل ثبت‌شده")])
        add(status="corrected", sign=1, vendor="فولاد گستر نمونه", original=original,
            description="فاکتور اصلاحی جایگزین",
            lines=[(seed.LINE[1], seed.REBAR, seed.REVERSAL_QUANTITY, "kg", reversal,
                    "تحویل اصلاح‌شده")])

    pending = int(seed.T(seed.PENDING_AMOUNT))
    for status, count in (("draft", seed.DRAFT_COUNT),
                          ("awaitingConfirmation", seed.AWAITING_COUNT)):
        for _ in range(count):
            add(status=status, sign=1, vendor="شرکت مصالح پایدار نمونه",
                description="فاکتور در انتظار بررسی",
                lines=[(seed.LINE[1], seed.REBAR, seed.PENDING_QUANTITY, "kg", pending,
                        "تحویل ثبت‌نشده")])
    return plan


def allocate(total: int, weights: list[int]) -> list[int]:
    """Split an adjustment across lines by weight, remainder on the last line."""
    if total == 0 or not weights:
        return [0] * len(weights)
    whole = sum(weights)
    parts = [round(total * weight / whole) for weight in weights[:-1]]
    return parts + [total - sum(parts)]


def build() -> str:
    org, project, actor = quote(seed.ORGANIZATION_ID), quote(seed.PROJECT_ID), quote(seed.ACTOR_ID)
    now = quote(seed.NOW.isoformat())
    out: list[str] = [
        "-- Generated by devhost/generate_seed_sql.py. Do not edit by hand.",
        "-- Mirrors the reference dataset in frontend/src/adapters/mock/.",
        "",
        "BEGIN;",
        "",
        "-- Project settings",
        "INSERT INTO finance_project_settings"
        "(id,organization_id,project_id,revision,gross_built_area,currency,effective_from,reason,created_by,created_at)"
        f" VALUES({quote(seed.SETTINGS_ID)},{org},{project},1,{quote(seed.GROSS_BUILT_AREA)},'IRR',"
        f"{quote(seed.SETTINGS_EFFECTIVE_FROM)},{quote(seed.SETTINGS_REASON)},{actor},{now});",
        "",
        "-- Finance resources",
    ]

    for resource_id, kind, code, title, base_unit, dimension, external_id in seed.RESOURCES:
        out.append(
            "INSERT INTO finance_resources"
            "(id,organization_id,project_id,resource_type,code,title,base_unit,dimension,"
            "external_resource_id,created_by,created_at)"
            f" VALUES({quote(resource_id)},{org},{project},{quote(kind)},{quote(code)},{quote(title)},"
            f"{quote(base_unit)},{quote(dimension)},{quote(external_id)},{actor},{now});")

    out += ["", "-- Estimate lines"]
    for line_id, resource_id, activity, assignment, quantity, price, source in seed.ESTIMATE_LINES:
        out.append(
            "INSERT INTO estimate_lines"
            "(id,organization_id,project_id,resource_id,activity_external_id,assignment_external_id,"
            "original_quantity,original_unit_price_irr,source,created_by,created_at)"
            f" VALUES({quote(line_id)},{org},{project},{quote(resource_id)},{quote(activity)},"
            f"{quote(assignment)},{quote(quantity)},{quote(price)},{quote(source)},{actor},{now});")

    out += ["", "-- Estimate revisions (the mock's revisedQuantity)"]
    for index, (line_id, revision, previous, new_quantity, reason) in enumerate(seed.ESTIMATE_REVISIONS, 1):
        out.append(
            "INSERT INTO estimate_revisions"
            "(id,organization_id,project_id,estimate_line_id,revision,previous_quantity,new_quantity,"
            "reason,created_by,created_at)"
            f" VALUES({quote(UUID(f'31000000-0000-4000-8000-{index:012d}'))},{org},{project},"
            f"{quote(line_id)},{revision},{quote(previous)},{quote(new_quantity)},{quote(reason)},"
            f"{actor},{now});")

    out += ["", "-- Price versions"]
    for price_id, resource_id, scope_kind, version, price, effective_from in seed.PRICE_VERSIONS:
        out.append(
            "INSERT INTO price_versions"
            "(id,organization_id,project_id,resource_id,scope_kind,version,unit_price_irr,"
            "effective_from,reason,created_by,created_at)"
            f" VALUES({quote(price_id)},{org},{project},{quote(resource_id)},{quote(scope_kind)},"
            f"{version},{quote(price)},{quote(effective_from)},{quote('ثبت نسخه قیمت')},{actor},{now});")

    out += ["", "-- Unit conversions"]
    for (conversion_id, scope_kind, version, source_unit, target_unit,
         dimension, factor, effective_from) in seed.UNIT_CONVERSIONS:
        out.append(
            "INSERT INTO unit_conversions"
            "(id,organization_id,project_id,scope_kind,version,source_unit,target_unit,dimension,"
            "factor,effective_from,reason,created_by,created_at)"
            f" VALUES({quote(conversion_id)},{org},{project},{quote(scope_kind)},{version},"
            f"{quote(source_unit)},{quote(target_unit)},{quote(dimension)},{quote(factor)},"
            f"{quote(effective_from)},{quote('تبدیل واحد پایه')},{actor},{now});")

    out += ["", "-- Progress snapshot references (the feed itself is served by the host port)"]
    for snapshot in seed.PROGRESS_SNAPSHOTS:
        out.append(
            "INSERT INTO progress_snapshot_refs"
            "(id,organization_id,project_id,progress_snapshot_id,source_file_version_id,"
            "source_file_name_safe,reporting_date,snapshot_status,imported_by,imported_at,created_at,"
            "host_snapshot_id,host_file_version_id)"
            f" VALUES({quote(snapshot['ref_id'])},{org},{project},"
            f"{quote(snapshot['progress_snapshot_id'])},{quote(snapshot['source_file_version_id'])},"
            f"{quote(snapshot['source_file_name_safe'])},{quote(snapshot['reporting_date'])},'ready',"
            f"{quote(seed.IMPORTER_ID)},{quote(snapshot['imported_at'].isoformat())},"
            f"{quote(snapshot['imported_at'].isoformat())},"
            # Core-shaped bigint identifiers, so a reseeded local database matches what the
            # adapter would have recorded rather than looking like a pre-integration row.
            f"{snapshot['host_snapshot_id']},{snapshot['host_file_version_id']});")

    override = seed.PROGRESS_OVERRIDE
    out += ["", "-- Manual progress override recorded by the mock feed"]
    out.append(
        "INSERT INTO progress_overrides"
        "(id,organization_id,project_id,estimate_line_id,progress_snapshot_ref_id,computed_value,"
        "override_value,reason,created_by,created_at)"
        f" VALUES({quote(override['id'])},{org},{project},{quote(override['estimate_line_id'])},"
        f"{quote(override['progress_snapshot_ref_id'])},{quote(override['computed_value'])},"
        f"{quote(override['override_value'])},{quote(override['reason'])},"
        f"{quote(override['created_by'])},{quote(override['created_at'].isoformat())});")

    plan = invoice_plan()
    counted = sum(line[4] * entry["sign"] for entry in plan
                  if entry["status"] in ("confirmed", "voided", "corrected")
                  for line in entry["lines"])
    out += ["", f"-- {len(plan)} invoices. Only confirmed, voided and corrected ones reach",
            f"-- the actual-cost figure: {counted // 10:,} toman.".replace(",", ",")]
    for entry in plan:
        confirmed = entry["status"] in ("confirmed", "voided", "corrected")
        version = {"draft": 1, "awaitingConfirmation": 2}.get(entry["status"], 3)
        # Discount, tax and shipping are left at zero. The line amounts here are the final
        # ones, and adding allocations that had to be unwound again to reach the same total
        # would obscure the plan without demonstrating anything the invoice tests do not
        # already cover.
        total = sum(line[4] for line in entry["lines"])
        out.append(
            "INSERT INTO invoices"
            "(id,organization_id,project_id,invoice_number,invoice_date,vendor_name,description,source,"
            "status,discount_irr,tax_irr,shipping_irr,other_costs_irr,final_amount_irr,"
            "financial_effect_sign,idempotency_key,original_invoice_id,version,submitted_by,"
            "confirmed_by,confirmed_at,created_at,updated_at)"
            f" VALUES({quote(entry['id'])},{org},{project},{quote(entry['number'])},"
            f"{quote(entry['date'])},{quote(entry['vendor'])},{quote(entry['description'])},"
            f"{quote(entry['source'])},{quote(entry['status'])},0,0,0,0,{total},"
            f"{entry['sign']},{quote(entry['idempotency_key'])},{quote(entry.get('original'))},"
            f"{version},{actor},"
            f"{actor if confirmed else 'NULL'},"
            f"{quote(entry['date'] + 'T09:15:00Z') if confirmed else 'NULL'},"
            f"{quote(entry['date'] + 'T08:30:00Z')},{quote(entry['date'] + 'T08:30:00Z')});")

        for position, (estimate_line, resource, quantity, unit, amount, note) in enumerate(entry["lines"]):
            unit_price = None if quantity is None else int(amount / float(quantity))
            line_id = UUID(f"41000000-0000-4000-8000-{entry['index'] * 10 + position:012d}")
            out.append(
                "INSERT INTO invoice_lines"
                "(id,organization_id,project_id,invoice_id,estimate_line_id,resource_id,quantity,unit,"
                "unit_price_snapshot_irr,raw_amount_irr,allocated_discount_irr,allocated_tax_irr,"
                "allocated_shipping_irr,allocated_other_costs_irr,final_line_amount_irr,description,created_at)"
                f" VALUES({quote(line_id)},{org},{project},{quote(entry['id'])},{quote(estimate_line)},"
                f"{quote(resource)},{quote(quantity)},{quote(unit)},{quote(unit_price)},{amount},"
                f"0,0,0,0,{amount},{quote(note)},{quote(entry['date'] + 'T08:30:00Z')});")

    out += ["", "-- Audit trail for the events the seed represents"]
    audit = [
        ("finance_settings.revised", "finance_project_settings", seed.SETTINGS_ID, seed.SETTINGS_REASON),
        ("estimate_line.revised", "estimate_revisions", seed.LINE[1], seed.ESTIMATE_REVISIONS[0][4]),
        ("price_version.created", "price_versions", seed.PRICE_VERSIONS[2][0], "ثبت قیمت پروژه‌ای میلگرد"),
        ("progress_override.created", "progress_overrides", override["id"], override["reason"]),
        ("invoice.confirmed", "invoices", invoice_uuid(1), None),
        ("invoice.confirmed", "invoices", invoice_uuid(9), None),
    ]
    for index, (action, entity_type, entity_id, reason) in enumerate(audit, 1):
        out.append(
            "INSERT INTO finance_audit_events"
            "(id,organization_id,project_id,actor_user_id,action,entity_type,entity_id,reason,occurred_at)"
            f" VALUES({quote(UUID(f'90000000-0000-4000-8000-{index:012d}'))},{org},{project},{actor},"
            f"{quote(action)},{quote(entity_type)},{quote(entity_id)},{quote(reason)},{now});")

    out += ["", "COMMIT;", ""]
    return "\n".join(out)


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT} ({len(OUT.read_text(encoding='utf-8').splitlines())} lines)")
