"""msp resources and assignments

Core's MSP tables record what was scheduled and how far along each task is. They record
nothing about *what* a task consumes: no resource, no unit, no quantity. So a Finance line
that says "1,329,121 kg of rebar" has never had anything on the Core side to compare itself
against, and every quantity in the progress feed has come back null.

These two tables close that gap. `msp_resources` is the Resource Sheet -- one row per
resource per snapshot -- and `msp_resource_assignments` is the task-by-resource grid
underneath it, which is where the quantity that a WBS rollup can actually use lives.

OWNERSHIP
This revision creates two tables named for Core's MSP domain. That is a deliberate decision
by the project owner: this Alembic chain manages the Finance schema *and* these two tables.
Existing Core tables -- `msp_snapshots`, `msp_tasks`, `msp_file_versions` -- are not
created, not altered, not referenced and not read for data here.

WHY THERE IS NO FOREIGN KEY INTO CORE
The production migration role has no REFERENCES privilege on Core tables, and there is no
administrator account available to grant one. A revision that declared those keys would
simply fail to apply. So `snapshot_id` and `task_uid` are ordinary columns, and the three
relationships below are LOGICAL -- upheld by the importer and checked by SQL, not by the
database:

    msp_resources.snapshot_id             -> msp_snapshots.id
    msp_resource_assignments.snapshot_id  -> msp_snapshots.id
    msp_resource_assignments.task_uid     -> msp_tasks.uid, within the same snapshot

WHAT THAT COSTS, SAID PLAINLY
A foreign key would have carried ON DELETE CASCADE, and Core does delete snapshots -- they
cascade from `projects`. Without it, deleting a project in Core leaves this table's rows
behind, pointing at a snapshot that no longer exists. Nothing breaks loudly; the rows simply
become unreachable clutter that still answers COUNT(*).

Two things stand in for the missing key, and both are deliberate:

  * the importer must verify the snapshot exists and the task belongs to it BEFORE
    publishing a feed, and fail the whole import if not -- see
    docs/MSP_PARSER_RESOURCE_ASSIGNMENT_IMPLEMENTATION_SPEC.md;
  * docs/sql/msp_resource_assignment_data_validation.sql counts orphans explicitly, so they
    are found by looking rather than by someone noticing a wrong total.

`msp_tasks` could not have been referenced in any case: it has `PRIMARY KEY (id)` and no
`UNIQUE (snapshot_id, uid)` for a composite key to point at.

WHAT THE NUMBERS MEAN
`resource_quantity` and `planned_quantity` are physical -- kilograms, cubic metres -- read
from MPXJ's Material field. `work` is hours. They are separate columns because Finance's
progress precedence prefers a physical quantity and treats work as a weaker fallback, and
that only works if the two can never arrive in the same place.

`standard_rate`, `source_cost` and `source_actual_cost` are reference only. The
authoritative price is `price_versions` and the authoritative actual cost is a confirmed
invoice; a rate typed into a Resource Sheet is neither.

IDENTITY, AND WHY GUID IS NOT IT
Two saved versions of one real schedule were compared: 1248 of 1248 task UIDs survived and
0 of 1248 GUIDs did -- saving the file under a new name regenerates every GUID while
changing nothing else. So `resource_uid` and `assignment_uid` are the identity, GUID is
kept only for diagnosis, and no cross-snapshot uniqueness is asserted anywhere. If UIDs
ever do move between versions, the result is rows that fail to match -- visible -- rather
than rows silently joined to the wrong thing.

The DDL below is the same statement tested in
`docs/sql/msp_resource_assignment_apply.sql`, which remains as the operational package for
anyone applying this outside Alembic.
"""

from alembic import op
from sqlalchemy import DDL

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


UPGRADE_SQL = """\
CREATE TABLE msp_resources (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id             bigint        NOT NULL,

    resource_uid            integer       NOT NULL,
    resource_guid           text,

    resource_name           text,
    native_type             text          NOT NULL,
    bambo_resource_type     text,

    resource_quantity       numeric(18,6),
    resource_quantity_unit  text,
    quantity_unit_source    text,

    initials                text,
    material_label          text,
    resource_group          text,
    code                    text,

    max_units               numeric(18,6),

    standard_rate           numeric(18,4),
    overtime_rate           numeric(18,4),
    cost_per_use            numeric(18,4),

    work                    numeric(18,6),
    actual_work             numeric(18,6),
    remaining_work          numeric(18,6),

    source_cost             numeric(18,4),
    source_actual_cost      numeric(18,4),
    source_remaining_cost   numeric(18,4),

    raw_fields_json         jsonb,
    created_at              timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT msp_resources_native_type_check
        CHECK (native_type IN ('WORK', 'MATERIAL', 'COST')),
    CONSTRAINT msp_resources_bambo_type_check
        CHECK (bambo_resource_type IS NULL
               OR bambo_resource_type IN ('material', 'labor', 'equipment', 'general_cost')),
    CONSTRAINT msp_resources_quantity_check
        CHECK (resource_quantity IS NULL OR resource_quantity >= 0),
    CONSTRAINT msp_resources_quantity_unit_source_check
        CHECK (quantity_unit_source IS NULL
               OR quantity_unit_source IN ('material_label', 'initials', 'custom_field', 'other')),
    CONSTRAINT msp_resources_snapshot_uid_key UNIQUE (snapshot_id, resource_uid),
    CONSTRAINT msp_resources_id_snapshot_key UNIQUE (id, snapshot_id)
);

CREATE INDEX msp_resources_snapshot_idx    ON msp_resources (snapshot_id);
CREATE INDEX msp_resources_native_type_idx ON msp_resources (snapshot_id, native_type);
CREATE INDEX msp_resources_guid_idx        ON msp_resources (resource_guid)
    WHERE resource_guid IS NOT NULL;

COMMENT ON TABLE  msp_resources IS
    'MSP Resource Sheet, one row per resource per snapshot. Finance reads it; the parser writes it.';
COMMENT ON COLUMN msp_resources.snapshot_id IS
    'Logically references msp_snapshots.id. No foreign key: the migration role has no REFERENCES privilege on Core. Orphans are counted by docs/sql/msp_resource_assignment_data_validation.sql.';
COMMENT ON COLUMN msp_resources.resource_uid IS
    'Native MSP Resource UID. The identity. GUID is regenerated on save and must not be used as one.';
COMMENT ON COLUMN msp_resources.resource_quantity IS
    'Physical quantity from MPXJ Resource.Material -- the Resource Sheet Quantity column. Not Work, not Max Units.';
COMMENT ON COLUMN msp_resources.resource_quantity_unit IS
    'Unit of resource_quantity. quantity_unit_source records which MSP field it was read from.';
COMMENT ON COLUMN msp_resources.bambo_resource_type IS
    'BAMBO-wide classification. NULL when MSP gives no basis to classify, which is every WORK resource so far.';
COMMENT ON COLUMN msp_resources.standard_rate IS
    'Reference only. The authoritative price history is price_versions.';


CREATE TABLE msp_resource_assignments (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id             bigint        NOT NULL,

    assignment_uid          integer       NOT NULL,
    task_uid                integer       NOT NULL,
    resource_uid            integer,

    units                   numeric(18,6),

    planned_work            numeric(18,6),
    actual_work             numeric(18,6),
    remaining_work          numeric(18,6),

    planned_quantity        numeric(18,6),
    actual_quantity         numeric(18,6),
    remaining_quantity      numeric(18,6),
    quantity_unit           text,

    assignment_work_complete_percent numeric(7,4),

    source_cost             numeric(18,4),
    source_actual_cost      numeric(18,4),
    source_remaining_cost   numeric(18,4),

    raw_fields_json         jsonb,
    created_at              timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT msp_resource_assignments_resource_fkey
        FOREIGN KEY (snapshot_id, resource_uid)
        REFERENCES msp_resources (snapshot_id, resource_uid) ON DELETE RESTRICT,
    CONSTRAINT msp_resource_assignments_snapshot_uid_key UNIQUE (snapshot_id, assignment_uid),
    CONSTRAINT msp_resource_assignments_planned_quantity_check
        CHECK (planned_quantity IS NULL OR planned_quantity >= 0),
    CONSTRAINT msp_resource_assignments_actual_quantity_check
        CHECK (actual_quantity IS NULL OR actual_quantity >= 0),
    CONSTRAINT msp_resource_assignments_remaining_quantity_check
        CHECK (remaining_quantity IS NULL OR remaining_quantity >= 0),
    CONSTRAINT msp_resource_assignments_quantity_unit_check
        CHECK (quantity_unit IS NOT NULL
               OR (planned_quantity IS NULL AND actual_quantity IS NULL
                   AND remaining_quantity IS NULL))
);

CREATE INDEX msp_resource_assignments_snapshot_idx ON msp_resource_assignments (snapshot_id);
CREATE INDEX msp_resource_assignments_task_idx     ON msp_resource_assignments (snapshot_id, task_uid);
CREATE INDEX msp_resource_assignments_resource_idx ON msp_resource_assignments (snapshot_id, resource_uid);

COMMENT ON TABLE  msp_resource_assignments IS
    'MSP resource assignments, one row per task-resource assignment per snapshot. Finance reads it; the parser writes it.';
COMMENT ON COLUMN msp_resource_assignments.snapshot_id IS
    'Logically references msp_snapshots.id. No foreign key: the migration role has no REFERENCES privilege on Core.';
COMMENT ON COLUMN msp_resource_assignments.task_uid IS
    'Logically references msp_tasks.uid within the same snapshot. No foreign key: no REFERENCES privilege on Core, and msp_tasks carries no UNIQUE (snapshot_id, uid) to point at.';
COMMENT ON COLUMN msp_resource_assignments.resource_uid IS
    'NULL where MSP left the assignment unlinked -- 12 of 727 in the reference file. Kept, so the row stays countable.';
COMMENT ON COLUMN msp_resource_assignments.planned_quantity IS
    'Physical quantity from MPXJ Assignment.Material. The task-granular figure a WBS rollup may use.';
COMMENT ON COLUMN msp_resource_assignments.actual_quantity IS
    'From MPXJ Assignment.ActualMaterial. NULL means not reported -- never zero by assumption.';
COMMENT ON COLUMN msp_resource_assignments.source_actual_cost IS
    'Reference only. The authoritative actual cost is a confirmed Finance invoice.';
"""


DOWNGRADE_SQL = """\
-- Assignments first: they hold the foreign key into msp_resources.
--
-- Unlike the operational rollback script, this does not ask whether the tables hold rows.
-- A downgrade is already an explicit instruction to undo a revision, and Alembic offers no
-- way to answer a prompt; the script in docs/sql/ is the one that refuses without
-- -v allow_data_loss=yes, and it is the safer thing to reach for on a live database.
--
-- No existing Core table is touched.
DROP TABLE IF EXISTS msp_resource_assignments;
DROP TABLE IF EXISTS msp_resources;
"""


def upgrade() -> None:
    op.execute(DDL(UPGRADE_SQL))


def downgrade() -> None:
    op.execute(DDL(DOWNGRADE_SQL))
