"""per-task schedule metrics that the finance side reads

Revision ID: 0010
Revises: 0009

A construction schedule in this shop carries far more on each task than dates and a
percentage. The planners keep, in custom Task columns, the physical quantity of the work
item, three weighting coefficients (rial, time, base), several progress measures (actual,
physical, planned) and the task's own cost. Those columns are what a finance rollup is
actually built on, and until now the importer read none of them.

They are TASK-level fields and Core owns them, so they live in a Core table, NOT in
Finance. `msp_task_metrics` is that table -- one row per task per snapshot, created by
this chain exactly as revision 0007 created `msp_resources` and
`msp_resource_assignments`.

WHY THE VALUES ARE READ BY ALIAS, NOT BY COLUMN INDEX
The planner named each column ("ضریب وزنی ریالی"); MS Project stored it in whatever
`NumberN` slot was free. The slot is not stable between files, the name is -- so the
reader maps by alias and this table's columns are named for the MEANING, never for a
`NumberN`.

WHY THERE IS NO FOREIGN KEY INTO CORE
Same reason 0007 gave for its two tables, and the same invariant 0009 pinned: exactly one
sanctioned key reaches into Core (`finance_task_resource_map.task_id`). This table keeps
the logical link `msp_resource_assignments` uses -- `snapshot_id` -> `msp_snapshots.id`
and `task_uid` -> `msp_tasks.uid` within that snapshot -- upheld by the importer, not by a
database constraint.

WHAT IS NOT HERE
No resource quantity (that is `msp_resources.resource_quantity`), no assignment quantity
(that is `msp_resource_assignments.*_quantity`), and nothing Finance computes for itself.
There are no value CHECK constraints: this table records what the file states, and a
schedule may legitimately carry a negative progress variance -- a check that rejected it
would turn a valid file into a failed import. The complete raw column set the file
carries, including columns nobody has mapped yet, is preserved separately in
`msp_tasks.raw_fields_json`.
"""

from alembic import op
from sqlalchemy import DDL


revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


UPGRADE_SQL = r"""
DO $precheck$
BEGIN
    IF to_regclass('msp_snapshots') IS NULL OR to_regclass('msp_tasks') IS NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '42P01',
            MESSAGE = '0010 requires the Core tables msp_snapshots and msp_tasks to '
                      'exist: msp_task_metrics is logically keyed to them. Create the '
                      'Core schema first, or do not run this revision here.';
    END IF;
END
$precheck$;

CREATE TABLE msp_task_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id bigint NOT NULL,
    task_uid integer NOT NULL,

    -- Physical quantities of the work item (آحجام / احجام).
    item_quantity numeric,
    item_quantity_text text,
    work_volume numeric,
    done_volume numeric,
    initial_volume numeric,
    work_volume_percent numeric,

    -- Weighting coefficients the rollup is built on.
    weight_time numeric,
    weight_rial numeric,
    weight_base numeric,
    weight_percent numeric,
    wf_time numeric,
    wf_rial numeric,
    wf_physical numeric,

    -- Progress measures the planners maintain beside the standard percentage.
    actual_progress numeric,
    actual_progress_percent numeric,
    physical_progress numeric,
    planned_progress numeric,
    planned_progress_component numeric,
    progress_variance numeric,

    -- The planners' own Jalali dates, kept as text: converting a calendar we have not
    -- confirmed would invent data.
    jalali_start text,
    jalali_finish text,

    -- The task's own cost, as the file states it. Finance still prices its lines itself;
    -- this is the schedule's number, recorded for comparison, never Finance's official one.
    task_cost numeric,
    task_actual_cost numeric,
    task_fixed_cost numeric,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (snapshot_id, task_uid)
);

COMMENT ON TABLE msp_task_metrics IS
    'One row per task per snapshot: the custom Task columns of an MPP schedule, read by '
    'the planner''s alias and owned by Core. Logically keyed to msp_snapshots.id and '
    'msp_tasks.uid; no FK, matching msp_resource_assignments.';
COMMENT ON COLUMN msp_task_metrics.task_uid IS
    'msp_tasks.uid within this snapshot -- the stable MSP identity, not the display ID.';

CREATE INDEX ix_msp_task_metrics_snapshot ON msp_task_metrics (snapshot_id);
"""


DOWNGRADE_SQL = r"""
DROP TABLE IF EXISTS msp_task_metrics;
"""


def upgrade() -> None:
    op.execute(DDL(UPGRADE_SQL))


def downgrade() -> None:
    op.execute(DDL(DOWNGRADE_SQL))
