-- GENERATED by scripts/demo/generate_core_mirror.py -- do not edit by hand.
-- Local Core mirror for the integration demo. Schema copied from the real Core
-- schema export; every ROW in these tables is synthetic and DEMO_LOCAL_ONLY.
-- This file is never applied to the Main/Core database and is not an Alembic
-- revision: Alembic owns the Finance schema only.

CREATE TABLE IF NOT EXISTS organizations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    code text,
    org_type text,
    status text DEFAULT 'active'::text NOT NULL,
    member_limit integer DEFAULT 10 NOT NULL,
    country text DEFAULT 'ایران'::text,
    province text,
    city text,
    street_address text,
    postal_code text,
    maps_embed text,
    contact_info text,
    logo_path text,
    landline_phone text,
    mobile_phone text,
    org_email text,
    website text,
    CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text,
    phone text,
    password_hash text,
    display_name text DEFAULT ''::text NOT NULL,
    avatar_path text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS projects (
    id text NOT NULL,
    organization_id uuid,
    name text NOT NULL,
    code text,
    address text,
    cover_image_path text,
    status text DEFAULT 'active'::text NOT NULL,
    start_date date,
    planned_end_date date,
    description text,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    built_area_sqm numeric,
    estimated_cost numeric(20,2),
    actual_cost_to_date numeric(20,2),
    cost_source text,
    cost_unit text,
    cost_updated_at timestamptz,
    cost_updated_by uuid,
    CONSTRAINT projects_actual_cost_to_date_check CHECK (actual_cost_to_date IS NULL OR actual_cost_to_date >= 0::numeric),
    CONSTRAINT projects_built_area_sqm_check CHECK (built_area_sqm IS NULL OR built_area_sqm >= 0::numeric),
    CONSTRAINT projects_cost_source_check CHECK (cost_source IS NULL OR (cost_source = ANY (ARRAY['MANUAL'::text, 'FINANCE_MODULE'::text]))),
    CONSTRAINT projects_cost_unit_check CHECK (cost_unit IS NULL OR cost_unit = 'IRR'::text),
    CONSTRAINT projects_estimated_cost_check CHECK (estimated_cost IS NULL OR estimated_cost >= 0::numeric),
    CONSTRAINT projects_status_check CHECK (status = ANY (ARRAY['active'::text, 'closed'::text, 'archived'::text])),
    CONSTRAINT projects_cost_updated_by_fkey FOREIGN KEY (cost_updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS organization_memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    organization_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT organization_memberships_role_check CHECK (role = ANY (ARRAY['org_admin'::text, 'editor'::text, 'viewer'::text, 'finance_viewer'::text, 'owner_client'::text])),
    CONSTRAINT organization_memberships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT organization_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT organization_memberships_pkey PRIMARY KEY (id),
    CONSTRAINT organization_memberships_organization_id_user_id_key UNIQUE (organization_id, user_id)
);

CREATE TABLE IF NOT EXISTS project_memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT project_memberships_role_check CHECK (role = ANY (ARRAY['viewer'::text, 'editor'::text, 'project_admin'::text])),
    CONSTRAINT project_memberships_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT project_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT project_memberships_pkey PRIMARY KEY (id),
    CONSTRAINT project_memberships_project_id_user_id_key UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    code text NOT NULL,
    category text DEFAULT 'customer'::text NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT roles_category_check CHECK (category = ANY (ARRAY['internal'::text, 'customer'::text])),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    module_key text NOT NULL,
    action_key text NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    group_name text NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code),
    CONSTRAINT permissions_module_key_action_key_key UNIQUE (module_key, action_key)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    organization_id uuid,
    project_id text,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id),
    CONSTRAINT user_roles_user_id_role_id_organization_id_project_id_key UNIQUE (user_id, role_id, organization_id, project_id)
);

CREATE TABLE IF NOT EXISTS user_permission_overrides (
    user_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    allowed boolean NOT NULL,
    CONSTRAINT user_permission_overrides_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT user_permission_overrides_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT user_permission_overrides_pkey PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS msp_file_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id text NOT NULL,
    version_number integer NOT NULL,
    original_filename text NOT NULL,
    stored_rel_path text NOT NULL,
    file_type text DEFAULT 'MPP'::text NOT NULL,
    detected_role text DEFAULT 'UNKNOWN'::text NOT NULL,
    size_bytes bigint NOT NULL,
    sha256 text NOT NULL,
    uploaded_by uuid,
    uploaded_at timestamptz DEFAULT now() NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    source_deleted_at timestamptz,
    source_deleted_by uuid,
    upload_role text,
    plan_intent text,
    intended_period_id bigint,
    archived_at timestamptz,
    archived_by uuid,
    CONSTRAINT msp_file_versions_detected_role_check CHECK (detected_role = ANY (ARRAY['MAIN'::text, 'TARGET'::text, 'ACTUAL'::text, 'UNKNOWN'::text])),
    CONSTRAINT msp_file_versions_file_type_check CHECK (file_type = 'MPP'::text),
    CONSTRAINT msp_file_versions_plan_intent_check CHECK (plan_intent IS NULL OR (plan_intent = ANY (ARRAY['INITIAL_BASELINE'::text, 'FORECAST_REVISION'::text, 'APPROVED_REVISED_BASELINE'::text]))),
    CONSTRAINT msp_file_versions_sha256_check CHECK (sha256 ~ '^[0-9a-f]{64}$'::text),
    CONSTRAINT msp_file_versions_size_bytes_check CHECK (size_bytes > 0),
    CONSTRAINT msp_file_versions_upload_role_check CHECK (upload_role IS NULL OR (upload_role = ANY (ARRAY['PLAN'::text, 'ACTUAL'::text]))),
    CONSTRAINT msp_file_versions_version_number_check CHECK (version_number > 0),
    CONSTRAINT msp_file_versions_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT msp_file_versions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT msp_file_versions_source_deleted_by_fkey FOREIGN KEY (source_deleted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT msp_file_versions_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT msp_file_versions_pkey PRIMARY KEY (id),
    CONSTRAINT msp_file_versions_id_project_id_key UNIQUE (id, project_id),
    CONSTRAINT msp_file_versions_project_id_version_number_key UNIQUE (project_id, version_number)
);

CREATE TABLE IF NOT EXISTS msp_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id text NOT NULL,
    file_version_id bigint NOT NULL,
    snapshot_type text NOT NULL,
    target_snapshot_id bigint,
    previous_snapshot_id bigint,
    source_filename text,
    source_version_number integer,
    display_label text,
    task_count integer DEFAULT 0 NOT NULL,
    parser_engine text,
    parser_warnings jsonb,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    status_date_jalali text,
    reporting_period_id bigint,
    CONSTRAINT msp_snapshots_snapshot_type_check CHECK (snapshot_type = ANY (ARRAY['TARGET'::text, 'ACTUAL'::text, 'RESCHEDULED'::text])),
    CONSTRAINT msp_snapshots_task_count_check CHECK (task_count >= 0),
    CONSTRAINT msp_snapshots_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT msp_snapshots_file_version_id_project_id_fkey FOREIGN KEY (file_version_id, project_id) REFERENCES msp_file_versions(id, project_id) ON DELETE RESTRICT,
    CONSTRAINT msp_snapshots_previous_snapshot_id_project_id_fkey FOREIGN KEY (previous_snapshot_id, project_id) REFERENCES msp_snapshots(id, project_id) ON DELETE RESTRICT,
    CONSTRAINT msp_snapshots_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT msp_snapshots_target_snapshot_id_project_id_fkey FOREIGN KEY (target_snapshot_id, project_id) REFERENCES msp_snapshots(id, project_id) ON DELETE RESTRICT,
    CONSTRAINT msp_snapshots_pkey PRIMARY KEY (id),
    CONSTRAINT msp_snapshots_id_project_id_key UNIQUE (id, project_id)
);

CREATE TABLE IF NOT EXISTS msp_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    snapshot_id bigint NOT NULL,
    uid integer,
    guid text,
    task_id integer,
    name text DEFAULT ''::text NOT NULL,
    wbs text,
    outline_number text,
    outline_level integer,
    start text,
    finish text,
    duration text,
    percent_complete numeric(7,4),
    percent_work_complete numeric(7,4),
    physical_percent_complete numeric(7,4),
    baseline_start text,
    baseline_finish text,
    baseline_duration text,
    baseline_cost numeric(18,4),
    number1 numeric(18,6),
    number3 numeric(18,6),
    number4 numeric(18,6),
    number13 numeric(18,6),
    number14 numeric(18,6),
    number18 numeric(18,6),
    text1 text,
    start1 text,
    finish1 text,
    raw_fields_json jsonb,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT msp_tasks_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES msp_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT msp_tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS media_files (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id text NOT NULL,
    kind text NOT NULL,
    file_path text NOT NULL,
    mime text,
    bytes bigint,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT media_files_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT media_files_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT media_files_pkey PRIMARY KEY (id)
);
