# -*- coding: utf-8 -*-
"""Generate the local Core mirror DDL from the real Core schema export.

The mirror exists so the demo database has the same *shape* as the shared BAMBO database:
Core tables and Finance tables side by side, with the logical references between them
visible in DBeaver. It is generated rather than hand-written for one reason -- a
hand-written mirror drifts, and a demo that shows the wrong column types teaches the wrong
thing about the integration.

WHAT IS AND IS NOT COPIED
Only the schema is taken from the export: table names, column names, types, nullability,
defaults and constraints. **No production row is copied by this script.** Everything the
mirror contains is written by `seed_core_mirror.py` and labelled DEMO_LOCAL_ONLY.

CONSTRAINTS THAT ARE DROPPED
A foreign key pointing at a table outside the mirror subset cannot be satisfied, so it is
omitted and reported. Nothing else is silently altered: if a CHECK cannot be reproduced the
generator says so rather than quietly relaxing it, because a mirror with looser rules than
Core would let the demo accept rows Core would reject.

Run:
    python -m scripts.demo.generate_core_mirror  [export.json]  >  core_mirror.sql
"""

import json
import re
import sys
from pathlib import Path

#: The smallest set that lets the demo show membership, RBAC, the project/organization
#: identity Finance references, and the MSP lineage behind progress snapshots.
MIRROR_TABLES = (
    "organizations", "users", "projects",
    "organization_memberships", "project_memberships",
    "roles", "permissions", "role_permissions", "user_roles",
    "user_permission_overrides",
    "msp_file_versions", "msp_snapshots", "msp_tasks",
    "media_files",
)

EXPORT_CANDIDATES = (
    Path.home() / "Documents" / "bambo_export" / "_core_columns.json",
    Path(r"C:\Users\atefe\AppData\Local\Temp\BAMBO_FINANCE_CORE_ALIGNMENT_AUDIT\_core_columns.json"),
)


def load_export(argv):
    if len(argv) > 1:
        return json.loads(Path(argv[1]).read_text(encoding="utf-8"))
    for candidate in EXPORT_CANDIDATES:
        if candidate.is_file():
            return json.loads(candidate.read_text(encoding="utf-8"))
    raise SystemExit("no Core schema export found; pass one as an argument")


def column_sql(column):
    """One column definition, with identity substituted for sequence defaults.

    A `nextval(...)` default names a sequence that does not exist in a fresh database.
    `GENERATED BY DEFAULT AS IDENTITY` is the same behaviour and creates its own sequence,
    and "by default" rather than "always" matters here: the mirror seeds explicit ids so
    they can be shown next to the Finance rows that reference them.
    """
    parts = [f'    {column["column"]} {column["type"]}']
    default = column.get("default")
    if default and default.startswith("nextval("):
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    elif default:
        parts.append(f"DEFAULT {default}")
    if not column["nullable"]:
        parts.append("NOT NULL")
    return " ".join(parts)


def referenced_table(definition):
    match = re.search(r"REFERENCES\s+([A-Za-z_][A-Za-z0-9_]*)", definition)
    return match.group(1) if match else None


def order_tables(tables, constraints):
    """Creation order: a table comes after everything it points at.

    A self-reference is ignored rather than treated as a cycle -- `msp_snapshots` points at
    itself through `previous_snapshot_id`, which PostgreSQL accepts inside one CREATE TABLE.
    """
    remaining, ordered = list(tables), []
    while remaining:
        progressed = False
        for table in list(remaining):
            needs = {referenced_table(c["definition"])
                     for c in constraints.get(table, []) if c["type"] == "FOREIGN KEY"}
            needs.discard(table)
            if needs <= set(ordered) | (needs - set(tables)):
                ordered.append(table)
                remaining.remove(table)
                progressed = True
        if not progressed:                      # a genuine cycle; emit the rest as-is
            ordered.extend(remaining)
            break
    return ordered


def main(argv):
    export = load_export(argv)
    columns, constraints = export["columns"], export["constraints"]
    missing = [t for t in MIRROR_TABLES if t not in columns]
    if missing:
        raise SystemExit(f"export does not describe: {', '.join(missing)}")

    dropped = []
    out = [
        "-- GENERATED by scripts/demo/generate_core_mirror.py -- do not edit by hand.",
        "-- Local Core mirror for the integration demo. Schema copied from the real Core",
        "-- schema export; every ROW in these tables is synthetic and DEMO_LOCAL_ONLY.",
        "-- This file is never applied to the Main/Core database and is not an Alembic",
        "-- revision: Alembic owns the Finance schema only.",
        "",
    ]
    for table in order_tables(MIRROR_TABLES, constraints):
        pieces = [column_sql(c) for c in columns[table]]
        for constraint in constraints.get(table, []):
            target = referenced_table(constraint["definition"])
            if constraint["type"] == "FOREIGN KEY" and target not in MIRROR_TABLES:
                dropped.append((table, constraint["name"], target))
                continue
            pieces.append(f'    CONSTRAINT {constraint["name"]} {constraint["definition"]}')
        out.append(f"CREATE TABLE IF NOT EXISTS {table} (")
        out.append(",\n".join(pieces))
        out.append(");")
        out.append("")

    if dropped:
        out.append("-- Foreign keys omitted because their target is outside the mirror subset.")
        out.append("-- They are listed rather than dropped silently: each one is a real Core")
        out.append("-- relationship that this demo simply does not model.")
        for table, name, target in dropped:
            out.append(f"--   {table}.{name} -> {target}")
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main(sys.argv)
